site_name: ParaViewGeophysics
site_author: Bane Sullivan
site_description: "Welcome to the documentation for the ParaViewGeophysics code repository. ParaViewGeophysics is a code base tailored to the visualization of spatially referenced data in the geosciences on the ParaView software platform. "
repo_url: https://github.com/banesullivan/ParaViewGeophysics
repo_name: PVGP on GitHub
site_url: http://pvgp.io/
edit_uri: ""
copyright: Copyright &copy 2017-2018, <a href="http://banesullivan.com">Bane Sullivan</a>

google_analytics:
  - 'UA-115959679-1'
  - 'auto'

extra:
  disqus: 'pvgp'
  social: # check https://fontawesome.com/ for more icons
    - type: 'github'
      link: 'https://github.com/banesullivan'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/bane-sullivan'
    - type: 'address-card'
      link: 'http://banesullivan.com'

theme:
    name: material
    palette:
        primary: 'blue-grey'
        accent: 'red'
    custom_dir: custom_theme
    favicon: 'img/globe_small.png'
    logo: 'img/globe_small.png'



markdown_extensions:
    - doc-include-import # custom docs include extension
    - doc-include-script # custom script include extension
    - smarty
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true
        guess_lang: true
    - meta # see this page: https://squidfunk.github.io/mkdocs-material/extensions/metadata/
    - footnotes # see this page: https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
    - pymdownx.b64 # local images
    - pymdownx.superfences # code snippets
    - pymdownx.inlinehilite #example: import the NumPy module by `#!py import numpy`
    - pymdownx.caret # ability to add exponents with caret: a^3
    - pymdownx.details # collapsible widgets
    - pymdownx.tasklist:
        custom_checkbox: true

plugins:
    - search

pages:
- Home: index.md

- Getting Started: Getting-Started.md

- Plugins & PVGPpy:
    - About PVGPpy: PVGPpy/About-PVGPpy.md
    - Build Your Own Plugins: PVGPpy/Build-Your-Own-Plugins.md
    - Readers:
        - Grids:
            - SGeMS Grid: PVGPpy/read/SGeMS-Grid.md
            - UBC Mesh Grid: PVGPpy/read/UBC-Mesh.md
            - UBC OcTree: PVGPpy/read/UBC-OcTree.md
            - PVGP Grid: PVGPpy/read/PVGP-Grid.md
        - Tables:
            - Binary Packed Data: PVGPpy/read/Binary-Packed-Data.md
            - Madagascar SSRSF: PVGPpy/read/Madagascar-SSRSF.md
            - Delimited Text: PVGPpy/read/Delimited-Text.md
            - GSLIB: PVGPpy/read/GSLIB.md

    - Filters:
        - Table to Uniform Grid: PVGPpy/filt/Table-to-Uniform-Grid.md
        - Flip Grid Axii: PVGPpy/filt/Flip-Grid-Axii.md
        - Reshape Table: PVGPpy/filt/Reshape-Table.md
        - Add Cell Connectivity to Points: PVGPpy/filt/Add-Cell-Connectivity-to-Points.md
        - Points to Tube: PVGPpy/filt/Points-to-Tube.md
        - Translate Origin of Grid: PVGPpy/filt/Translate-Origin-of-Grid.md
        - Normalize Array: PVGPpy/filt/Normalize-Array.md
        - Animate Tunnel Boring Machine: PVGPpy/filt/Animate-TBM.md
        - Correlate Arrays: PVGPpy/filt/Correlate-Arrays.md
        - UBC Add Model: PVGPpy/filt/UBC-Add-Model.md


- PV Macros:
    - About pvmacros: pvmacros/About-pvmacros.md
    - Export:
        - Export as VTKjs:  pvmacros/export/exportVTKjs.md
    - Vis:
        - Camera: pvmacros/vis/Camera.md
        - Clip Through:  pvmacros/vis/Clip-Through.md
        - Many Slices Along Points:  pvmacros/vis/Many-Slices-Along-Points.md
        - Many Slices Along Axis:  pvmacros/vis/Slices-Along-Axis.md

- Examples:
    - Slice Model Along PolyLine: Examples/Slice-Model-Along-PolyLine.md
    - Editing the Axes: Examples/Edit-Axes.md
    - Editing the Render View: Examples/Edit-Render-View.md
    - Save Camera Views: Examples/Save-Camera-Locations.md
    - Understand VTK Data Types: Examples/Understand-VTK.md

- Resources:
    - Color Maps: cmaps.md
    - Scripts:
        - About Scripts: Scripts/About-Scripts.md
        - Example Script: Scripts/Example-Script.md
    - Entering Virtual Reality: Virtual-Reality/Entering-Virtual-Reality.md

- Development Guide:
    - Contributing: Dev-Guide/Contributing-to-PVGP.md
    - Repo Structure: Dev-Guide/Repo-Structure.md

- Features to Come: Upcoming.md
